APP_NAME = "NAWI OIML Test Report System"

OIML_R76_1_2006 = "OIML R76-1:2006"
OIML_R76_2_2007 = "OIML R76-2:2007"

EVALUATION_DRAFT = "DRAFT"
EVALUATION_IN_PROGRESS = "IN_PROGRESS"
EVALUATION_COMPLETE = "COMPLETE"
EVALUATION_FINALIZED = "FINALIZED"

TEST_NOT_TESTED = "NOT_TESTED"
TEST_IN_PROGRESS = "IN_PROGRESS"
TEST_COMPLETE = "COMPLETE"

RESULT_PASS = "PASS"
RESULT_FAIL = "FAIL"
RESULT_NA = "NA"